/**
 * Writes the background-free app assets to ../assets: the logo and its color variants, the macOS and
 * Android app icons, and the menu bar glyph, each as SVG and PNG, plus manifest.json.
 * The cat's states live in the Rive file, so there are no per-state images here.
 * Run with `npm run export:assets`.
 */
import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {bundle} from '@remotion/bundler';
import {renderStill, selectComposition} from '@remotion/renderer';
import {IconArt, IconKind} from '../src/icons/IconArt';
import {LittermateName, littermatePalettes} from '../src/cat/palettes';

const ROOT = path.resolve(__dirname, '..');
const OUT = path.resolve(ROOT, '..', 'assets');

const LITTERMATE_NAMES = Object.keys(littermatePalettes()) as LittermateName[];
const ANDROID_DENSITIES = {mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192};
const mipmaps = (name: string): [string, number][] =>
  Object.entries(ANDROID_DENSITIES).map(([d, s]) => [`icons/android/mipmap-${d}/${name}.png`, s]);
const MAC_SIZES = [16, 32, 64, 128, 256, 512, 1024];
const LOGO_SIZES = [256, 512, 1024];

/** Every icon file: its art, its SVG path, and the PNGs to render as [path, size]. */
const ICONS: {kind: IconKind; svg: string; png: [string, number][]}[] = [
  {kind: 'mark', svg: 'logo/yumi-mark.svg', png: LOGO_SIZES.map((s) => [`logo/yumi-mark-${s}.png`, s])},
  {kind: 'markMono', svg: 'logo/yumi-mark-mono.svg', png: [['logo/yumi-mark-mono-512.png', 512]]},
  {kind: 'markWhite', svg: 'logo/yumi-mark-white.svg', png: [['logo/yumi-mark-white-512.png', 512]]},
  ...LITTERMATE_NAMES.map((n): {kind: IconKind; svg: string; png: [string, number][]} => (
    {kind: `mark-${n}`, svg: `logo/littermates/yumi-${n}.svg`, png: [[`logo/littermates/yumi-${n}-512.png`, 512]]})),
  {kind: 'macos', svg: 'icons/macos/yumi-appicon.svg', png: MAC_SIZES.map((s) => [`icons/macos/appicon-${s}.png`, s])},
  {kind: 'menubar', svg: 'icons/macos/yumi-menubar.svg', png: [['icons/macos/menubar-18.png', 18], ['icons/macos/menubar-36.png', 36]]},
  {kind: 'androidForeground', svg: 'icons/android/ic_launcher_foreground.svg', png: [['icons/android/ic_launcher_foreground-432.png', 432]]},
  {kind: 'androidBackground', svg: 'icons/android/ic_launcher_background.svg', png: [['icons/android/ic_launcher_background-432.png', 432]]},
  {kind: 'androidLegacy', svg: 'icons/android/ic_launcher.svg', png: mipmaps('ic_launcher')},
  {kind: 'androidRound', svg: 'icons/android/ic_launcher_round.svg', png: mipmaps('ic_launcher_round')},
  {kind: 'playStore', svg: 'icons/android/playstore.svg', png: [['icons/android/playstore-512.png', 512]]},
];

/** A standalone SVG file: namespaced, without the inline style React adds for the live preview. */
const svgFile = (el: React.ReactElement) => {
  let s = renderToStaticMarkup(el);
  if (!s.startsWith('<svg xmlns')) s = s.replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ');
  return s.replace(/^(<svg[^>]*?) style="[^"]*"/, '$1');
};

const write = (rel: string, data: string) => {
  const file = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(file), {recursive: true});
  fs.writeFileSync(file, data);
};


const main = async () => {
  for (const dir of ['logo', 'icons', 'poses', 'svg', 'png', 'video']) fs.rmSync(path.join(OUT, dir), {recursive: true, force: true});

  for (const {kind, svg} of ICONS) write(svg, svgFile(React.createElement(IconArt, {kind, size: 1024})));
  console.log('svg done');

  const serveUrl = await bundle({entryPoint: path.join(ROOT, 'src', 'index.ts')});
  for (const {kind, png} of ICONS) {
    const inputProps = {kind};
    const comp = await selectComposition({serveUrl, id: 'YumiIcon', inputProps});
    for (const [rel, size] of png) {
      fs.mkdirSync(path.dirname(path.join(OUT, rel)), {recursive: true});
      await renderStill({composition: {...comp, width: size, height: size}, serveUrl, inputProps, imageFormat: 'png', output: path.join(OUT, rel)});
    }
    console.log(kind, 'done');
  }

  const manifest = {
    note: 'Generated by character/remotion/scripts/export-assets.ts; do not edit by hand.',
    logo: {svg: 'logo/yumi-mark.svg', png: 'logo/yumi-mark-{size}.png', sizes: LOGO_SIZES},
    macos: {
      appIcon: {svg: 'icons/macos/yumi-appicon.svg', png: 'icons/macos/appicon-{size}.png', sizes: MAC_SIZES},
      menuBar: {svg: 'icons/macos/yumi-menubar.svg', png: ['icons/macos/menubar-18.png', 'icons/macos/menubar-36.png'], template: true},
    },
    android: {
      adaptive: {foreground: 'icons/android/ic_launcher_foreground.svg', background: 'icons/android/ic_launcher_background.svg'},
      legacy: 'icons/android/mipmap-{density}/ic_launcher.png',
      round: 'icons/android/mipmap-{density}/ic_launcher_round.png',
      densities: ANDROID_DENSITIES,
      playStore: 'icons/android/playstore-512.png',
    },
    logoVariants: {
      mono: 'logo/yumi-mark-mono.svg',
      white: 'logo/yumi-mark-white.svg',
      littermates: Object.fromEntries(LITTERMATE_NAMES.map((n) => [n, `logo/littermates/yumi-${n}.svg`])),
    },
  };
  write('manifest.json', JSON.stringify(manifest, null, 2) + '\n');
  console.log('manifest done');
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
