/**
 * Writes the background-free app assets to ../assets:
 * one SVG, a PNG set (@1x/@2x/@3x), and a seamless WebM loop with alpha per cursor state, plus manifest.json.
 * Run with `npm run export:assets`.
 */
import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {bundle} from '@remotion/bundler';
import {renderMedia, renderStill, selectComposition} from '@remotion/renderer';
import {YumiCat} from '../src/cat/YumiCat';
import {CatState, poseFor} from '../src/cat/poses';
import {CAT} from '../src/cat/catParts';
import {LOOP, LOOP_CAT, STILL_PAD} from '../src/scenes/loopSpec';

const ROOT = path.resolve(__dirname, '..');
const OUT = path.resolve(ROOT, '..', 'assets');
const FPS = 30;

/** Each state's key frame for the stills: a moment that reads clearly on its own. */
const STATES: {state: CatState; frame: number}[] = [
  {state: 'idle', frame: 0},
  {state: 'listening', frame: 0},
  {state: 'thinking', frame: 10},
  {state: 'moving', frame: 3},
  {state: 'acting', frame: 5},
  {state: 'waitingForUser', frame: 0},
  {state: 'paused', frame: 0},
  {state: 'done', frame: 0},
  {state: 'stuck', frame: 8},
];

const [vx, vy, vw] = CAT.viewBox.split(' ').map(Number);
/** The paws, where a pounce lands, as a fraction of the cat's square, without and with the still padding. */
const PAWS = {x: (CAT.centerX - vx) / vw, y: (CAT.groundY - vy) / vw};
const m = vw * STILL_PAD;
const PAWS_PADDED = {x: (CAT.centerX - vx + m) / (vw + 2 * m), y: (CAT.groundY - vy + m) / (vw + 2 * m)};
const round = (n: number) => Math.round(n * 10) / 10;

const main = async () => {
  for (const dir of ['svg', 'png', 'video']) fs.mkdirSync(path.join(OUT, dir), {recursive: true});

  for (const {state, frame} of STATES) {
    const svg = renderToStaticMarkup(React.createElement(YumiCat, {size: 512, pad: STILL_PAD, ...poseFor(state, frame, FPS, LOOP)}))
      .replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ')
      .replace(/ style="[^"]*"/, '');
    fs.writeFileSync(path.join(OUT, 'svg', `yumi-${state}.svg`), svg);
  }
  console.log('svg done');

  const serveUrl = await bundle({entryPoint: path.join(ROOT, 'src', 'index.ts')});
  for (const {state, frame} of STATES) {
    const inputProps = {state};
    const still = await selectComposition({serveUrl, id: 'YumiPose', inputProps});
    for (const scale of [1, 2, 3]) {
      await renderStill({composition: still, serveUrl, inputProps, frame, scale, imageFormat: 'png',
        output: path.join(OUT, 'png', `yumi-${state}@${scale}x.png`)});
    }
    const loop = await selectComposition({serveUrl, id: 'YumiMoodLoop', inputProps});
    await renderMedia({composition: loop, serveUrl, inputProps, codec: 'vp9', imageFormat: 'png', pixelFormat: 'yuva420p',
      outputLocation: path.join(OUT, 'video', `yumi-${state}.webm`)});
    console.log(state, 'done');
  }

  const manifest = {
    note: 'Stand-in assets until yumi-cat.riv exists (OBJ-10). Generated by character/remotion/scripts/export-assets.ts; do not edit by hand.',
    states: STATES.map(({state}) => state),
    svg: {size: 512, file: 'svg/yumi-{state}.svg', hotspot: {x: round(512 * PAWS_PADDED.x), y: round(512 * PAWS_PADDED.y)}},
    png: {size: 256, scales: [1, 2, 3], file: 'png/yumi-{state}@{scale}x.png', hotspot1x: {x: round(256 * PAWS_PADDED.x), y: round(256 * PAWS_PADDED.y)}},
    video: {
      size: 512, fps: FPS, frames: LOOP, codec: 'vp9', alpha: true, file: 'video/yumi-{state}.webm',
      hotspot: {x: round(LOOP_CAT.left + LOOP_CAT.size * PAWS.x), y: round(LOOP_CAT.top + LOOP_CAT.size * PAWS.y)},
    },
  };
  fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  console.log('manifest done');
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
